development:
  adapter: postgresql
  encoding: unicode
  database: fin_development
  pool: 5
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: fin_test
  pool: 5
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: fin_production
  pool: 5
  host: localhost
