development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: fin_development
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: fin_test
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  database: fin_test
  username: postgres
  password:
