source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'pg'
#gem 'sass-rails', '~> 4.0.3'
gem 'sass', '~> 3.4', '>= 3.4.20'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
#gem 'turbolinks'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'sorcery'
gem 'rails_12factor', group: :production
#gem 'delayed_job_active_record'
gem 'unicorn'

# stylingz
#gem 'bourbon', '~> 4.2', '>= 4.2.6'
#gem 'neat', '~> 1.7', '>= 1.7.2'
#gem 'bitters', '~> 1.1'
#gem 'refills', '~> 0.1.0'

gem 'awesome_print', group: :development

gem 'lograge'

# nw sync
gem 'mechanize'
# amex sync
gem 'watir'
gem 'selenium-webdriver'
gem 'headless'

gem 'string-similarity'
